services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: it_priorities
    ports:
      - "5432:5432"
    volumes:
      - it-priorities-db:/var/lib/postgresql/data

volumes:
  it-priorities-db:
